language: node_js
os:
  - linux
  - osx
env:
  - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: latest
node_js:
  - "10"
  - "9"
  - "8"
before_install:
  - export CHROME_BIN=chromium-browser
script:
  - npm run coverage
  - npm run test-chrome
  - npm run test-firefox
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run test-safari; fi
  - codecov
