language: node_js
os:
  - linux
  - osx
node_js:
  - "10"
  - "9"
  - "8"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
script:
  - npm run coverage
  - npm run test-chrome
  - npm run test-firefox
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run text-safari; fi
  - codecov
